knpu_oauth2_client:
  clients:
    tgstation:
      type: generic
      provider_class: App\Provider\TgStation
      client_id: "%env(TG_CLIENT_ID)%"
      client_secret: "%env(TG_CLIENT_SECRET)%"
      redirect_route: auth.tgstation.finish
      redirect_params: {}
      use_state: true
    discord:
      type: discord
      client_id: "%env(DISCORD_CLIENT_ID)%"
      client_secret: "%env(DISCORD_CLIENT_SECRET)%"
      redirect_route: auth.discord.finish
      use_state: true
