security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: "auto"
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            provider: app_user_provider
            custom_authenticators:
                - App\Security\TgStationAuthenticator
                - App\Security\DiscordAuthenticator
            lazy: true
            logout:
                path: /logout
                target: app.home
            entry_point: App\Controller\AuthController
            remember_me:
                secret: '%kernel.secret%'
                lifetime: 604800
                always_remember_me: true
    access_control:

    providers:
        app_user_provider:
            id: App\Security\UserProvider
        # used to reload user from session & other features (e.g. switch_user)
when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4
                time_cost: 3
                memory_cost: 10
