twig:
    file_name_pattern: "*.twig"
    globals:
        servers: '@App\Service\ServerInformationService'
        allow_list: "%app.allow_list%"
        admin_only: "%app.allow_nonadmins%"
        secret: "%env(APP_SECRET)%"
    date:
        format: "Y-m-d H:i:s"
    form_themes: ["bootstrap_5_layout.html.twig"]
when@test:
    twig:
        strict_variables: true
