permissions: write-all
name: Production Deployments
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true
on:
  release:
    types: [published]
  workflow_dispatch:
jobs:
  build-and-ship:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image (no push)
        run: |
          docker build -t statbus:latest .

      - name: Save Docker image to tarball
        run: |
          docker save statbus:latest -o statbus.tar

      - name: SCP image to remote server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_KEY }}
          source: "statbus.tar"
          target: "~/"

      - name: SSH and deploy container with docker-compose
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_KEY }}
          script: |
            echo "Stopping and removing previous container..."
            docker compose down statbus 
            docker image rm statbus --force

            echo "Loading fresh Docker image..."
            docker image load --input ~/statbus.tar

            echo "Removing old tarball..."
            rm -rf ~/statbus.tar

            echo "Deploying container via docker-compose..."
            cd ~/serv
            docker compose up statbus -d

            echo "Running database migrations..."
            docker compose exec statbus php bin/console doctrine:migrations:migrate --no-interaction --em=statbus

            echo "Clearing Symfony cache..."
            docker compose exec statbus php bin/console cache:clear

            echo "✅ Deployment complete!"