name: Deploy Test

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build-and-ship:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image (no push)
        run: |
          docker build -t statbus-test:latest .

      - name: Save Docker image to tarball
        run: |
          docker save statbus-test:latest -o statbus-test.tar

      - name: SCP image to remote server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_KEY }}
          source: "statbus-test.tar"
          target: "~/"

      - name: SSH and deploy container with docker-compose
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_KEY }}
          script: |
            echo "Loading Docker image..."
            docker image load --input ~/statbus-test.tar

            # echo "Removing old tarball..."
            # rm -rf ~/statbus-test.tar

            # echo "Deploying container via docker-compose..."
            # cd ~/serv
            # docker compose down statbus-test && docker compose up statbus-test -d

            # echo "Running database migrations..."
            # docker compose exec statbus-test php bin/console doctrine:migrations:migrate --no-interaction --em=statbus

            # echo "Clearing Symfony cache..."
            # docker compose exec statbus-test php bin/console cache:clear

            echo "✅ Test deployment done via Traefik!"